name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: drumandbytes/reusable-actions/.github/workflows/python-action-ci.yml@v1
    with:
      test-dependencies: "pytest pytest-asyncio 'aiohttp>=3.9.0,<3.12' pyyaml packaging aioresponses"
      required-files: |
        action.yml
        .github/scripts/update_versions.py
